image:
  registry: localhost:5001
  repository: grafana
  tag: 12.3.1
persistence:
  enabled: true
  type: pvc
  size: 2Gi
resources:
  limits:
    cpu: 200m
    memory: 512Mi
adminPassword: "admin"
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.observability.svc.cluster.local
      access: proxy
      isDefault: true
